steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fp-crud-note', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fp-crud-note']

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'fp-crud-note', '--image', 'gcr.io/$PROJECT_ID/fp-crud-note', '--platform', 'managed', '--region', 'asia-southeast2', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/fp-crud-note'